language: ruby
rvm:
- 2.2.2
script: script/cibuild
before_script:
- openssl aes-256-cbc -K $encrypted_5727dd035aee_key -iv $encrypted_5727dd035aee_iv -in script/.ssh/bozo.enc -out script/.ssh/bozo -d
- chmod 600 script/.ssh/bozo
- eval `ssh-agent -s`
- ssh-add script/.ssh/bozo
